name: Keep Render Awake

on:
  schedule:
    - cron: '*/14 * * * *'  # Every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render app
        run: curl -s https://maniraj.onrender.com/ > /dev/null
